version: '2'
services:
   alisql:
    image: mysql:5.7-1
    environment:
      - MYSQL_ROOT_PASSWORD=19930221
    ports:
      - '13306:3306'
    volumes:
      - './data:/var/lib/mysql'
      - './bin_log:/var/lib/mysql/bin_log:rw'
      - './mysql.cnf:/etc/mysql/conf.d/mysql.cnf'